import { Scan, ScanSummary } from './types'

export const DEMO_SCAN: Scan = {
  id: 'demo',
  productName: 'Terra Snacks Original',
  category: 'Packaged Food',
  score: 74,
  status: 'POTENTIAL_ISSUE',
  imageUrl: '/demo/product-label.svg',
  imageWidth: 400,
  imageHeight: 600,
  createdAt: 'Sep 14, 2026, 11:30 PM',
  extractedData: {
    product_name: 'Terra Snacks Original Crunchy Tortilla Crisps',
    mrp: '₹ 40.00',
    net_quantity: '52 g',
    country_of_origin: 'India',
    best_before: '6 months from packaging',
    manufacturer: 'ABC Foods India Pvt. Ltd., Plot 14, MIDC Industrial Area, Andheri (E), Mumbai 400072',
    consumer_care: 'NOT DETECTED',
  },
  ocrResults: [
    { text: 'TERRA SNACKS', confidence: 0.99, bbox: [35, 55, 365, 130] },
    { text: 'Country of Origin: India', confidence: 0.92, bbox: [30, 333, 235, 358] },
    { text: 'MAX RETAIL PRICE ₹ 40.00', confidence: 0.97, bbox: [240, 326, 393, 380] },
    { text: 'Best Before: 6 months from packaging', confidence: 0.81, bbox: [30, 363, 360, 390] },
    { text: 'Net Qty: 52 g', confidence: 0.95, bbox: [242, 386, 315, 410] },
    { text: 'MANUFACTURED & MARKETED BY: ABC Foods India Pvt. Ltd.', confidence: 0.93, bbox: [30, 449, 360, 492] },
  ],
  complianceResults: [
    {
      requirementId: 'mrp',
      label: 'Maximum Retail Price (MRP)',
      status: 'PASS',
      confidence: 0.97,
      detected: '₹ 40.00 (inclusive of all taxes)',
      reason: 'MRP declaration clearly detected in bold type with high OCR confidence (97%). Complies with size and font requirements.',
      evidence: 'Detected text "MAX RETAIL PRICE ₹ 40.00" at coordinates [240, 326, 393, 380].',
      source: 'Legal Metrology (Packaged Commodities) Rules, 2011',
      sourceSection: 'Rule 6(1)(f) — Retail sale price of the package',
      bbox: [240, 326, 393, 380],
    },
    {
      requirementId: 'net_qty',
      label: 'Net Quantity Declaration',
      status: 'PASS',
      confidence: 0.95,
      detected: '52 g',
      reason: 'Net weight declared in standard metric units (grams). Positioned prominently and legible.',
      evidence: 'Detected text "Net Qty: 52 g" at coordinates [242, 386, 315, 410].',
      source: 'Legal Metrology (Packaged Commodities) Rules, 2011',
      sourceSection: 'Rule 6(1)(b) — Net quantity in standard units of weight/measure',
      bbox: [242, 386, 315, 410],
    },
    {
      requirementId: 'country_of_origin',
      label: 'Country of Origin',
      status: 'PASS',
      confidence: 0.92,
      detected: 'India',
      reason: 'Country of origin is explicitly mentioned on the principal display panel.',
      evidence: 'Detected text "Country of Origin: India" at coordinates [30, 333, 235, 358].',
      source: 'Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
      sourceSection: 'Rule 6(1)(k) — Country of origin or manufacture',
      bbox: [30, 333, 235, 358],
    },
    {
      requirementId: 'best_before',
      label: 'Date of Manufacture / Expiry',
      status: 'NEEDS_REVIEW',
      confidence: 0.76,
      detected: '6 months from packaging',
      reason: 'Relative best-before duration declared ("6 months from packaging") without a specific packaging month/year detected on label artwork. Requires human verification.',
      evidence: 'Detected text "Best Before: 6 months from packaging" at coordinates [30, 363, 360, 390]. Specific packing date stamp missing from printed mockup.',
      source: 'Legal Metrology (Packaged Commodities) Rules, 2011',
      sourceSection: 'Rule 6(1)(c) — Month and year in which commodity is manufactured or pre-packed',
      bbox: [30, 363, 360, 390],
    },
    {
      requirementId: 'manufacturer',
      label: 'Name and Complete Address of Manufacturer',
      status: 'PASS',
      confidence: 0.93,
      detected: 'ABC Foods India Pvt. Ltd., Plot 14, MIDC Industrial Area, Andheri (E), Mumbai 400072',
      reason: 'Manufacturer entity and geographic address with postal PIN code (400072) successfully identified.',
      evidence: 'Detected full manufacturer block at coordinates [30, 449, 360, 492].',
      source: 'Legal Metrology (Packaged Commodities) Rules, 2011',
      sourceSection: 'Rule 6(1)(a) — Name and complete address of the manufacturer',
      bbox: [30, 449, 360, 492],
    },
    {
      requirementId: 'consumer_care',
      label: 'Consumer Care Helpline Details',
      status: 'POTENTIAL_ISSUE',
      confidence: 0.89,
      detected: null,
      reason: 'Mandatory consumer contact details (telephone number, email address, or designated postal address for consumer complaints) were NOT detected on the package.',
      evidence: 'No consumer care phone number, email ID, or complaint address identified across all OCR text segments.',
      source: 'Legal Metrology (Packaged Commodities) Rules, 2011',
      sourceSection: 'Rule 6(1)(h) — Name, address, telephone number, and email of person or office for consumer complaints',
      bbox: null,
    },
  ],
}

export const SCAN_OAT_MILK: Scan = {
  id: 'scan-001',
  productName: 'Organic Oat Milk',
  category: 'Beverage',
  score: 96,
  status: 'PASS',
  imageUrl: '/demo/product-label.svg',
  imageWidth: 400,
  imageHeight: 600,
  createdAt: 'Today, 10:42 AM',
  extractedData: {
    product_name: 'Organic Oat Milk',
    mrp: '₹ 180.00',
    net_quantity: '1000 mL',
    country_of_origin: 'India',
    manufacturer: 'PureBeverages Ltd, Bengaluru 560001',
    consumer_care: 'care@purebev.in, 1800-123-4567',
  },
  ocrResults: [],
  complianceResults: [
    {
      requirementId: 'mrp',
      label: 'Maximum Retail Price (MRP)',
      status: 'PASS',
      confidence: 0.98,
      detected: '₹ 180.00',
      reason: 'Compliant with Rule 6(1)(f)',
      evidence: 'MRP clearly stated',
      source: 'Legal Metrology Rules, 2011',
      sourceSection: 'Rule 6(1)(f)',
      bbox: [240, 326, 393, 380],
    },
    {
      requirementId: 'net_qty',
      label: 'Net Quantity',
      status: 'PASS',
      confidence: 0.96,
      detected: '1000 mL',
      reason: 'Compliant with Rule 6(1)(b)',
      evidence: '1000 mL standard metric unit',
      source: 'Legal Metrology Rules, 2011',
      sourceSection: 'Rule 6(1)(b)',
      bbox: [242, 386, 315, 410],
    },
  ],
}

export const SCAN_PUREGLOW: Scan = {
  id: 'scan-002',
  productName: 'PureGlow Serum',
  category: 'Cosmetic',
  score: 82,
  status: 'NEEDS_REVIEW',
  imageUrl: '/demo/product-label.svg',
  imageWidth: 400,
  imageHeight: 600,
  createdAt: 'Yesterday, 4:18 PM',
  extractedData: {
    product_name: 'PureGlow Vitamin C Serum',
    mrp: '₹ 699.00',
    net_quantity: '30 ml',
    consumer_care: 'support@pureglow.co',
  },
  ocrResults: [],
  complianceResults: [
    {
      requirementId: 'mrp',
      label: 'Maximum Retail Price (MRP)',
      status: 'PASS',
      confidence: 0.94,
      detected: '₹ 699.00',
      reason: 'Valid MRP declaration',
      evidence: 'MRP ₹ 699',
      source: 'Legal Metrology Rules, 2011',
      sourceSection: 'Rule 6(1)(f)',
      bbox: [240, 326, 393, 380],
    },
    {
      requirementId: 'best_before',
      label: 'Batch & Expiry',
      status: 'NEEDS_REVIEW',
      confidence: 0.68,
      detected: 'EXP: 11/27',
      reason: 'Batch number printing is faint and needs manual check.',
      evidence: 'EXP date found, BATCH prefix illegible',
      source: 'Drugs and Cosmetics Rules / Legal Metrology',
      sourceSection: 'Rule 6(1)(c)',
      bbox: [30, 363, 360, 390],
    },
  ],
}

export const SCAN_HISTORY: ScanSummary[] = [
  { id: 'scan-001', productName: 'Organic Oat Milk', category: 'Beverage carton', score: 96, status: 'PASS', createdAt: 'Today, 10:42 AM', thumb: 'OM' },
  { id: 'scan-002', productName: 'PureGlow Serum', category: 'Cosmetic bottle', score: 82, status: 'NEEDS_REVIEW', createdAt: 'Yesterday, 4:18 PM', thumb: 'PG' },
  { id: 'demo', productName: 'Terra Snacks Original', category: 'Flexible pouch', score: 74, status: 'POTENTIAL_ISSUE', createdAt: 'Sep 14, 2026', thumb: 'TS' },
  { id: 'scan-004', productName: 'ABC Basmati Rice 5kg', category: 'Grains & Pulses', score: 88, status: 'PASS', createdAt: 'Sep 10, 2026', thumb: 'BR' },
  { id: 'scan-005', productName: 'XYZ Herbal Shampoo', category: 'Personal Care', score: 64, status: 'POTENTIAL_ISSUE', createdAt: 'Sep 08, 2026', thumb: 'HS' },
  { id: 'scan-006', productName: 'NutriBar Almond Plus', category: 'Packaged Food', score: 91, status: 'PASS', createdAt: 'Sep 04, 2026', thumb: 'NB' },
]

export const ANALYTICS_DATA = {
  totalScans: 248,
  passRate: 75,
  avgScore: 83,
  issueRate: 8,
  scansOverTime: [
    { month: 'Apr', scans: 18, passed: 14, issues: 1 },
    { month: 'May', scans: 24, passed: 19, issues: 2 },
    { month: 'Jun', scans: 32, passed: 26, issues: 3 },
    { month: 'Jul', scans: 45, passed: 35, issues: 4 },
    { month: 'Aug', scans: 61, passed: 48, issues: 5 },
    { month: 'Sep', scans: 68, passed: 52, issues: 5 },
  ],
  commonIssues: [
    { label: 'Missing Consumer Care Helpline (Rule 6.1.h)', percentage: 42, count: 28 },
    { label: 'Unreadable or Faint MRP Font (Rule 6.1.f)', percentage: 21, count: 14 },
    { label: 'Relative Date without Packing Month/Year (Rule 6.1.c)', percentage: 19, count: 13 },
    { label: 'Incomplete Manufacturer Address or PIN (Rule 6.1.a)', percentage: 12, count: 8 },
    { label: 'Non-Standard Units of Weight/Measure (Rule 6.1.b)', percentage: 6, count: 4 },
  ],
  categoryBreakdown: [
    { category: 'Packaged Food', percentage: 44 },
    { category: 'Beverages', percentage: 24 },
    { category: 'Cosmetics & Personal Care', percentage: 18 },
    { category: 'Household Commodities', percentage: 14 },
  ],
}

export function getScanById(id: string): Scan {
  if (id === 'scan-001') return SCAN_OAT_MILK
  if (id === 'scan-002') return SCAN_PUREGLOW
  return DEMO_SCAN
}
